import anm from 'anm';
anm('.vertical-p').y(25);
anm('.vertical-m').y(-25);
anm('.horizontal-p').x(50);
anm('.horizontal-m').x(-50);
anm('.scale-p').scale(50);
anm('.scale-m').scale(-50);
anm('.rotate-p').rotate(50);
anm('.rotate-m').rotate(-50);
anm('.opacity-p').opacity(75);
